# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghswitch < Formula
  desc "GitHub-aware git toolkit — switch identities, manage branches, commit, sync, and open PRs"
  homepage "https://github.com/MadhuS-1605/ghswitch"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MadhuS-1605/ghswitch/releases/download/v0.2.2/ghswitch_darwin_amd64.tar.gz"
      sha256 "457e3728939a20c979dcfa7ce4a1ea74f9c3106540a9975d985fb51321c6166d"

      define_method(:install) do
        bin.install "ghswitch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MadhuS-1605/ghswitch/releases/download/v0.2.2/ghswitch_darwin_arm64.tar.gz"
      sha256 "24e1964d06fb7c2e73952abb624954232e23a21275a87f9491f4e93770a3743f"

      define_method(:install) do
        bin.install "ghswitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadhuS-1605/ghswitch/releases/download/v0.2.2/ghswitch_linux_amd64.tar.gz"
      sha256 "e855db46392523241ad16476141118e4890ae6e2b854309526768a700230998e"
      define_method(:install) do
        bin.install "ghswitch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadhuS-1605/ghswitch/releases/download/v0.2.2/ghswitch_linux_arm64.tar.gz"
      sha256 "c387abb2df16900cfda380adb6eba542ee068f91673c91a74e27d99041091a62"
      define_method(:install) do
        bin.install "ghswitch"
      end
    end
  end
end
